version: '2'

services:
  # Serveur MySQL
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${GLOBAL_USER}
      MYSQL_PASSWORD: ${GLOBAL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
  # Wordpress (latest)
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '${WP_PORT}:80'
    restart: always
    volumes:
      - /docker_preprod/${DOCK_NAME}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${GLOBAL_USER}
      WORDPRESS_DB_PASSWORD: ${GLOBAL_PASSWORD}
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD} 
