version: '2'

services:
  # Serveur MySQL
  db:
    image: mysql:5.7
    volumes:
      - ${DOCK_NAME}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${GLOBAL_USER}
      MYSQL_PASSWORD: ${GLOBAL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
  # Wordpress (latest)
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '${WP_PORT}:80'
    restart: always
    volumes: ['${DOCK_NAME}:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  # FTP Server (pure-ftpd)
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "${FTP_PORT}:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/${DOCK_NAME}/data:/home/username/"
      - "/${DOCK_NAME}/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${GLOBAL_USER}
      FTP_USER_PASS: ${GLOBAL_PASSWORD}
      FTP_USER_HOME: /home/${GLOBAL_USER}
    restart: always
volumes:
  ${DOCK_NAME}:
